
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  matchmaking-api:
    build:
      context: .
      dockerfile: Matchmaking.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      - rabbitmq
      - redis

  matchmaking-worker:
    build:
      context: .
      dockerfile: Matchmaking.Worker/Dockerfile
    environment:
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      - rabbitmq
      - redis