
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-datax:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-datax:/data

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=matchmaking
      - POSTGRES_PASSWORD=matchmaking
      - POSTGRES_DB=matchmaking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  matchmaking-api:
    build:
      context: .
      dockerfile: Matchmaking.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=matchmaking;Username=matchmaking;Password=matchmaking
      - Jwt__Key=super-secret-dev-key-please-change-0123456789abcdef
      - Jwt__Issuer=matchmaking
      - Admin__Username=Sancar
      - Admin__Password=Sancar123
    depends_on:
      - rabbitmq
      - redis
      - postgres

  matchmaking-worker:
    build:
      context: .
      dockerfile: Matchmaking.Worker/Dockerfile
    environment:
      - RabbitMq__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq-datax:
  redis-datax:
  postgres-data: